(() => {
'use strict';
const OFFICIAL=window.CAPY_OFFICIAL||[], TRIVIA=window.CAPY_TRIVIA||[], CULTURE=window.CAPY_CULTURE||{};
const STATES=['Berlin','Baden-Württemberg','Bayern','Brandenburg','Bremen','Hamburg','Hessen','Mecklenburg-Vorpommern','Niedersachsen','Nordrhein-Westfalen','Rheinland-Pfalz','Saarland','Sachsen','Sachsen-Anhalt','Schleswig-Holstein','Thüringen'];
const LABELS={'history-politics':'History & politics','sports':'Sports','music-artists':'Music & artists','film-tv-pop':'Film, TV & pop culture','art-literature-philosophy':'Art, books & ideas','everyday-germany':'Everyday Germany'};
const TOPICS=[['Random','dice'],['Democracy','ballot'],['Politics','building'],['History','clock'],['Society','people'],['Local','pin']];
const TRIVIA_START_LIVES=3, TRIVIA_MAX_LIVES=5;
const KEY='capybuerger-v3', $=id=>document.getElementById(id);
const fresh=()=>({settings:{name:'',state:'Berlin',humour:'classic',reminders:true,translations:true},daily:null,dailyHistory:[],exam:null,examHistory:[],trivia:null,triviaHistory:[],trophies:{quick:0,long:0},recentOfficial:[],recentTrivia:[],mastered:[]});
let state=fresh();try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&typeof saved==='object')state={...state,...saved,settings:{...state.settings,...saved.settings},trophies:{...state.trophies,...saved.trophies}}}catch(e){}
const officialIds=new Set(OFFICIAL.map(q=>q.id));
state.mastered=Array.isArray(state.mastered)?[...new Set(state.mastered.filter(id=>officialIds.has(id)))]:[];
if(!STATES.includes(state.settings.state))state.settings.state='Berlin';
if(!['classic','spicy'].includes(state.settings.humour))state.settings.humour='classic';
if(state.trivia?.mode==='long')state.trivia.lives=Math.min(TRIVIA_MAX_LIVES,Math.max(0,Number(state.trivia.lives)||0));
const triviaIds=new Set(TRIVIA.map(q=>q.id));
if(state.trivia){const ids=state.trivia.mode==='quick'?state.trivia.cards?.map(c=>c.id):[state.trivia.card?.id].filter(Boolean);if(!ids?.every(id=>triviaIds.has(id)))state.trivia=null}
state.recentTrivia=Array.isArray(state.recentTrivia)?state.recentTrivia.filter(id=>triviaIds.has(id)).slice(-220):[];
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){toast('Your browser is not saving progress. Check private browsing or storage settings.')}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const ICON_PATHS={
 dice:'<rect x="3" y="3" width="18" height="18" rx="4"/><circle cx="8" cy="8" r=".8"/><circle cx="16" cy="8" r=".8"/><circle cx="12" cy="12" r=".8"/><circle cx="8" cy="16" r=".8"/><circle cx="16" cy="16" r=".8"/>',
 ballot:'<rect x="3" y="10" width="18" height="11" rx="2"/><path d="M9 14h6M9 4l3 3 4-5"/>',
 building:'<path d="M2 9 12 3l10 6M4 10h16M3 21h18M6 11v9M12 11v9M18 11v9"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',
 people:'<circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2 20c0-4 2-6 6-6s6 2 6 6M13 15c4-2 8 1 9 5"/>',
 pin:'<path d="M12 22s8-7 8-13a8 8 0 0 0-16 0c0 6 8 13 8 13Z"/><circle cx="12" cy="9" r="2.5"/>',
 brush:'<path d="m9 15 10-10 2 2-10 10M18 5l1-2 2 2-2 2M9 15c-4-1-6 1-6 6 5 0 7-2 6-6Z"/><path d="m7 17-2 2"/>',
 book:'<path d="M12 5c-4-2-7-2-10-1v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-3-1-6-1-10 1ZM12 5v15"/>',
 music:'<path d="M10 17V5l10-2v12"/><ellipse cx="7" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/>',
 flask:'<path d="M9 2h6M10 2v8L4 21h16l-6-11V2M7 16h10"/>',
 home:'<path d="m2 11 10-8 10 8M4 10v11h16V10"/>',
 flame:'<path d="M12 22c-5 0-8-3-8-8 0-4 3-6 5-10 0 4 2 5 3 7 2-2 3-4 3-7 4 4 5 7 5 10 0 5-3 8-8 8Z"/><path d="M12 21c-2 0-3-2-3-4 0-1 1-3 3-5 2 2 3 4 3 5 0 2-1 4-3 4Z"/>',
 exam:'<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/>',
 bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-7l0-7Z"/>'
 ,ball:'<circle cx="12" cy="12" r="9"/><path d="m12 8 4 3-1.5 4h-5L8 11l4-3ZM3.5 9l4.5 2M20.5 9 16 11M7 20l2.5-5M17 20l-2.5-5"/>'
 ,film:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 4v16M17 4v16M3 9h4M17 9h4M3 15h4M17 15h4M7 4l10 16M17 4 7 20"/>'
};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${ICON_PATHS[name]||ICON_PATHS.dice}</svg>`}
function localDay(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}
function dayIndex(){const [y,m,d]=localDay().split('-').map(Number);return Math.floor((Date.UTC(y,m-1,d)-Date.UTC(y,0,1))/86400000)%365}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function datesAgo(d,n){const t=new Date(`${d}T12:00:00Z`);t.setUTCDate(t.getUTCDate()-n);return t.toISOString().slice(0,10)}
function lastDaily(){return state.dailyHistory.find(x=>x.date===localDay())}
function streak(){const days=new Set(state.dailyHistory.map(x=>x.date));let d=localDay();if(!days.has(d))d=datesAgo(d,1);let n=0;while(days.has(d)){n++;d=datesAgo(d,1)}return n}
function accuracy(){const h=state.dailyHistory;return h.length?`${Math.round(100*h.reduce((a,x)=>a+x.correct,0)/(h.length*5))}%`:'—'}
function line(mood){const spicy=state.settings.humour==='spicy';const sets={neutral:spicy?['No mames, this one looks interesting.','Give it a shot, güey. I believe in that pinche brain.']:['Take a breath. Reason first, guess second.','A thoughtful answer beats a lucky guess.'],happy:spicy?['A huevo! That pinche brain works.','Mira nada más, güey. You nailed it.']:['A fine deduction. I approve.','Quite right. Evidence is your friend.'],wrong:spicy?['No manches, güey. Read the explanation.','Chale. That answer went straight to the bin.']:['An error is useful data. Read why.','A curious hypothesis. The evidence disagrees.'],win:spicy?['A huevo, campeón. Take your damn trophy!']:['An excellent result. This trophy is well earned.'],lose:spicy?['Pinche tough round. You can get it next time, güey.']:['A difficult round. We learn, then try again.']};return shuffle(sets[mood]||sets.neutral)[0]}
let currentScreen='home', studyTopic='Random', studyCard=null, studyNumber=0;
function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),4700)}
function go(screen){if(!['home','daily','study','exam','trivia'].includes(screen))return;currentScreen=screen;document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===screen+'Screen'));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===screen));render();window.scrollTo({top:0,behavior:'instant'})}
function face(mood='neutral',caption=line(mood)){return `<div class="capy-line"><div class="capy-avatar" role="img" aria-label="Capy ${esc(mood)}" style="background-image:url(assets/capy-${mood==='win'?'happy':mood==='lose'?'sassy':mood==='wrong'?'sassy':mood==='happy'?'happy':'neutral'}.png)"></div><span>${esc(caption)}</span></div>`}
function officialById(id){return OFFICIAL.find(x=>x.id===id)}
function triviaById(id){return TRIVIA.find(x=>x.id===id)}
function cardFor(q){return {id:q.id,order:shuffle([0,1,2,3]),choice:null}}
function isSensitive(q){return /(holocaust|nazi|nationalsozial|hitler|eichmann|birkenau|konzentrationslager|auschwitz|dachau|sachsenhausen|buchenwald|ravensbrück|jüdisch|juden|shoah|gestapo|verfolgung|massenmord|genozid|kriegsverbrechen|wannsee|weiße rose|white rose|scholl|antisemit|persecution|extermination|genocide|concentration camp|deportation|rechtsextrem|far-right attack|olympics attack|israeli olympians|olympia-attentat)/i.test(q.question.de+' '+q.question.en+' '+q.explanation_en)}
function answerMarkup(q,card,mode){const sensitive=isSensitive(q);const art=q.visual?.kind==='prompt'?`<figure class="prompt-art"><img src="${esc(q.visual.images[0])}" alt="${esc(q.visual.alt?.[0]||'Original schematic study illustration') }" loading="lazy"><figcaption>${esc(q.visual.credit)} · <a href="${esc(q.visual.images[0])}" target="_blank" rel="noopener">Zoom image ↗</a></figcaption></figure>`:'';return `<article class="question"><span class="eyebrow">GERMAN · ENGLISH${q.updated_as_of?` · UPDATED ${esc(q.updated_as_of)}`:``}</span><div class="de" lang="de">${esc(q.question.de)}</div>${state.settings.translations?`<p class="en" lang="en">${esc(q.question.en)}</p>`:''}${art}</article><div class="answers">${card.order.map((index,pos)=>{const selected=card.choice===index,done=card.choice!==null,klass=done?(index===q.correct_index?' correct':selected?' wrong':''):'';return `<button type="button" class="answer${klass}" data-answer-mode="${mode}" data-answer="${index}" ${done?'disabled':''}><span class="letter">${'ABCD'[pos]}</span>${q.visual?.kind==='choices'?`<img class="choice-art" src="${esc(q.visual.images[index])}" alt="${esc(q.visual.alt?.[index]||'Study illustration '+(index+1))}" loading="lazy">`:''}<span><b lang="de">${esc(q.options[index].de)}</b>${state.settings.translations?`<small lang="en">${esc(q.options[index].de==='Bundestag'&&q.options[index].en==='Bundestag'?'German federal parliament':q.options[index].en)}</small>`:''}</span></button>`}).join('')}</div>${q.visual?.kind==='choices'?`<p class="visual-credit">${esc(q.visual.credit)}</p>`:''}${card.choice!==null?`<div class="feedback"><strong>${card.choice===q.correct_index?'Correct!':'Not quite. The answer is '+esc(q.options[q.correct_index].de)+'.'}</strong>${esc(q.explanation_en)}${mode==='trivia'&&q.sources?.length?`<br><a href="${esc(q.sources[0])}" target="_blank" rel="noopener noreferrer">Read source ↗</a>`:''}</div>${sensitive?face('neutral','Read the context carefully; this history matters.'):face(card.choice===q.correct_index?'happy':'wrong')}`:(sensitive?face('neutral','Take your time with this history.'):face('neutral'))}`}
function markSeen(type,id){const k=type==='trivia'?'recentTrivia':'recentOfficial';state[k]=(state[k]||[]).filter(x=>x!==id);state[k].push(id);state[k]=state[k].slice(-220)}
function masterCorrect(id,choice){const q=officialById(id);if(q&&choice===q.correct_index&&!state.mastered.includes(id))state.mastered.push(id)}
function masteredStats(){const pool=OFFICIAL.filter(q=>!q.state||q.state===state.settings.state),known=new Set(state.mastered),correct=pool.filter(q=>known.has(q.id)).length;return {correct,total:pool.length}}
function pickOfficial(pool,exclude=[]){let p=pool.filter(q=>!exclude.includes(q.id));if(!p.length)throw Error('Not enough verified questions for this selection.');const fresh=p.filter(q=>!(state.recentOfficial||[]).includes(q.id));return shuffle(fresh.length?fresh:p)[0]}
function home(){const idx=dayIndex(),f=CULTURE.facts?.[idx],w=CULTURE.words?.[idx],phrase=CULTURE.phrases?.[idx%(CULTURE.phrases?.length||1)];if(!f||!w)return;
const h=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Berlin',hour:'2-digit',hourCycle:'h23'}).format(new Date()));$('greeting').textContent=(h<12?'GOOD MORNING':h<18?'GOOD AFTERNOON':'GOOD EVENING')+(state.settings.name?', '+state.settings.name.toLocaleUpperCase():'');$('factCategory').textContent=f.category;$('factTitle').textContent=f.title;$('factSummary').textContent=f.detail?f.body:(f.body.toLowerCase().includes(String(f.answer).toLowerCase())?f.body:`${f.answer}. ${f.body}`);$('factDetail').textContent=f.detail||'';$('factDetail').classList.add('hidden');$('factReveal').classList.toggle('hidden',!f.detail);$('factReveal').textContent='Tell me more →';$('factReveal').setAttribute('aria-expanded','false');$('factSource').href=f.source||'#';$('factSource').dataset.available=f.source?'1':'0';$('factSource').classList.add('hidden');$('wordLabel').textContent=w.kind==='slang'?'SLANG WORD OF THE DAY':'WORD OF THE DAY';$('wordText').textContent=w.de;$('wordMeaning').textContent=w.en;$('phraseText').textContent=phrase?.[0]||'';$('phraseMeaning').textContent=phrase?.[1]||'';
const headings=[['Five questions. One more day.','A little daily thinking never killed anyone.'],['Your brain called. It wants five.','Capy has brought your next assignment.'],['Small quest. Big brain.','One practice today, one step closer.'],['Five for the streak.','I have faith in you. Mostly.'],['The republic can wait five minutes.','Five questions, then you may rest.']];const [title,sub]=headings[idx%5];$('heroHeading').textContent=title;$('heroSub').textContent=sub;$('heroButton').textContent=lastDaily()?'See today’s result →':'Study now →';$('streakCount').textContent=streak();$('dailyAccuracy').textContent=accuracy();$('trophyCount').textContent=Object.values(state.trophies).filter(Boolean).length;$('examTeaser').textContent=state.examHistory.length?`Best: ${Math.max(...state.examHistory.map(x=>x.correct))}/33 · Goal: 33/33`:'Your next goal: 33 / 33';$('reminder').classList.toggle('hidden',!state.settings.reminders||!!lastDaily());
const progress=masteredStats(),pct=progress.total?progress.correct/progress.total*100:0;$('masteredState').textContent=state.settings.state;$('masteredCount').textContent=`${progress.correct} / ${progress.total}`;$('masteredPct').textContent=`${progress.correct?Math.max(1,Math.floor(pct)):0}%`;$('masteredFill').style.width=`${pct}%`;$('masteredMeter').setAttribute('aria-valuenow',String(progress.correct));$('masteredMeter').setAttribute('aria-valuemax',String(progress.total));$('masteredMeter').setAttribute('aria-label',`Official questions mastered for ${state.settings.state}`);
const html=TOPICS.map(([t,glyph])=>`<button class="topic" data-topic="${t}"><span class="topic-icon">${icon(glyph)}</span>${esc(t==='Local'?state.settings.state:t)}</button>`).join('');$('homeTopics').innerHTML=html;syncStatePickers()}
function makeDaily(){const date=localDay();if(state.daily&&state.daily.date===date)return;if(lastDaily())return;const general=OFFICIAL.filter(q=>!q.state),local=OFFICIAL.filter(q=>q.state===state.settings.state);const selected=[];for(let i=0;i<4;i++)selected.push(pickOfficial(general,selected.map(x=>x.id)));selected.push(pickOfficial(local,selected.map(x=>x.id)));state.daily={date,cards:shuffle(selected).map(cardFor),index:0};save()}
function daily(){if(lastDaily()){const result=lastDaily(),last=state.daily?.date===result.date?state.daily.cards[4]:null,q=last?officialById(last.id):null;$('dailyHeading').textContent=state.settings.humour==='spicy'?'You did it, güey.':'A fine day of study.';$('dailySub').textContent='Your next daily five opens tomorrow.';$('dailyProgress').innerHTML=Array.from({length:5},()=>'<i class="done"></i>').join('');$('dailyContent').innerHTML=`<div class="result"><span class="eyebrow">TODAY'S DAILY PRACTICE</span><p class="big-score">${result.correct}/5</p><p>${Math.round(result.correct/5*100)}% accuracy · streak ${streak()} days</p>${face('happy',result.correct===5?line('happy'):line('happy'))}</div>${q?`<h2>Your last answer</h2>${answerMarkup(q,last,'daily')}`:''}<button class="ghost" data-go="home">Back home</button>`;return}
makeDaily();const d=state.daily,q=officialById(d.cards[d.index].id),card=d.cards[d.index];$('dailyHeading').textContent=`Question ${d.index+1} of 5`;$('dailySub').textContent=['Five tiny battles. This is one.','Capy brought questions and questionable confidence.',state.settings.humour==='spicy'?'Your brain is warming up, güey.':'Your brain is warming up nicely.','Almost done. The streak is watching.','Last one. Finish like the intellectual you are.'][(dayIndex()+d.index)%5];$('dailyProgress').innerHTML=d.cards.map((x,i)=>`<i class="${i<d.index||x.choice!==null?'done':''}"></i>`).join('');$('dailyContent').innerHTML=answerMarkup(q,card,'daily')+(card.choice!==null?`<div class="actions"><button class="primary" data-action="daily-next">${d.index===4?'Finish today →':'Next question →'}</button></div>`:'')}
function answerDaily(index){const d=state.daily;if(!d||lastDaily())return;if(d.date!==localDay()){state.daily=null;save();daily();return}const card=d.cards[d.index];if(card.choice!==null)return;card.choice=index;markSeen('official',card.id);masterCorrect(card.id,index);save();daily()}
function nextDaily(){const d=state.daily;if(!d||d.cards[d.index].choice===null)return;if(d.date!==localDay()){state.daily=null;save();daily();return}if(d.index<4){d.index++;save();daily();window.scrollTo(0,0);return}state.dailyHistory=state.dailyHistory.filter(x=>x.date!==d.date);state.dailyHistory.push({date:d.date,correct:d.cards.filter(x=>x.choice===officialById(x.id).correct_index).length,total:5});state.dailyHistory=state.dailyHistory.slice(-400);state.daily=null;save();daily();home()}
function nextStudy(){const pool=OFFICIAL.filter(q=>studyTopic==='Local'?q.state===state.settings.state:studyTopic==='Random'?(!q.state||q.state===state.settings.state):!q.state&&q.category===studyTopic);if(!pool.length){$('studyContent').innerHTML='<p>No verified questions in this topic yet.</p>';return}const q=pickOfficial(pool,studyCard?[studyCard.id]:[]);studyCard=cardFor(q);studyNumber++;study()}
function study(){const html=TOPICS.map(([t,glyph])=>`<button class="topic ${t===studyTopic?'selected':''}" data-topic="${t}"><span class="topic-icon">${icon(glyph)}</span>${esc(t==='Local'?state.settings.state:t)}</button>`).join('');$('studyTopics').innerHTML=html;$('studyHeading').textContent=studyTopic==='Random'?state.settings.humour==='spicy'?'Another one, güey.':'Another question awaits.':studyTopic==='Local'?state.settings.state:studyTopic;$('studyCount').textContent=`QUESTION ${studyNumber} · ${studyTopic==='Random'?'ALL TOPICS':studyTopic.toUpperCase()}`;if(!studyCard){nextStudy();return}const q=officialById(studyCard.id);$('studyContent').innerHTML=answerMarkup(q,studyCard,'study')+`<div class="actions"><button class="primary" data-action="study-next">Next question →</button></div>`}
function startExam(){const general=OFFICIAL.filter(q=>!q.state),local=OFFICIAL.filter(q=>q.state===state.settings.state);if(general.length<30||local.length<3){toast('The verified exam bank is incomplete for this state.');return}const a=[];for(let i=0;i<30;i++)a.push(pickOfficial(general,a.map(x=>x.id)));for(let i=0;i<3;i++)a.push(pickOfficial(local,a.map(x=>x.id)));state.exam={state:state.settings.state,startedAt:Date.now(),cards:shuffle(a).map(cardFor),index:0,finished:false};save();exam()}
function examTime(){return state.exam?Math.max(0,3600-Math.floor((Date.now()-state.exam.startedAt)/1000)):0}
function finishExam(){const e=state.exam;if(!e||e.finished)return;e.finished=true;const right=e.cards.filter(x=>x.choice===officialById(x.id).correct_index).length;state.examHistory.unshift({date:localDay(),correct:right,total:33,state:e.state});state.examHistory=state.examHistory.slice(0,30);save()}
function quitExam(){if(!state.exam||state.exam.finished)return;if(!window.confirm('Finish this exam now? Unanswered questions count as incorrect.'))return;finishExam();exam()}
function exam(){const e=state.exam;if(e&&!e.finished&&examTime()===0)finishExam();$('examHeading').textContent=e?.finished?'Exam complete. Capy has notes.':e?'Question '+(e.index+1)+' of 33':'33 questions. One goal.';$('examSub').textContent=e&&!e.finished?`✓ ${e.cards.filter(c=>c.choice===officialById(c.id).correct_index).length} correct · ✕ ${e.cards.filter(c=>c.choice!==null&&c.choice!==officialById(c.id).correct_index).length} wrong · ${Math.floor(examTime()/60)}:${String(examTime()%60).padStart(2,'0')} left`:'Pass at 17/33. Aim for 33/33.';
if(e?.finished){const record=state.examHistory[0],right=record?.correct??0;$('examContent').innerHTML=`<div class="result"><span class="eyebrow">YOUR RESULT · ${esc(e.state)}</span><p class="big-score">${right}/33</p><p>${33-right} incorrect · ${right>=17?'Test passed!':'Keep practising.'}</p>${face(right===33?'win':right>=17?'happy':'wrong',right===33?'33/33. I am officially impressed.':line(right>=17?'happy':'wrong'))}<p>Best exam score: ${Math.max(...state.examHistory.map(x=>x.correct))}/33</p></div><button class="primary" data-action="exam-new">Try a new exam →</button>${historyHTML()}`;return}
if(!e){$('examContent').innerHTML=`<div class="result exam-rules"><span class="eyebrow">THE RULES</span><p>30 general + 3 from ${esc(state.settings.state)}. 60 minutes, just like the real exam. No repeated questions in a run.</p></div><button class="primary" data-action="exam-new">Start mock exam →</button>${historyHTML()}`;return}
const card=e.cards[e.index],q=officialById(card.id);$('examContent').innerHTML=`<div class="progress">${e.cards.map((x,i)=>`<i class="${i<e.index||x.choice!==null?'done':''}"></i>`).join('')}</div>${answerMarkup(q,card,'exam')}${card.choice!==null?`<div class="actions"><button class="primary" data-action="exam-next">${e.index===32?'See results →':'Next question →'}</button></div>`:''}<button class="exit-round" data-action="exam-finish">Finish exam early</button>`;}
function historyHTML(){return state.examHistory.length?`<h2>Previous exams</h2><ul class="history">${state.examHistory.slice(0,10).map(x=>`<li><span>${esc(x.date)} · ${esc(x.state)}</span><b>${x.correct}/33 ${x.correct>=17?'✓':'·'}</b></li>`).join('')}</ul>`:''}
function examAnswer(i){const e=state.exam;if(!e||e.finished)return;if(examTime()===0){finishExam();exam();return}const c=e.cards[e.index];if(c.choice!==null)return;c.choice=i;markSeen('official',c.id);masterCorrect(c.id,i);save();exam()}
function examNext(){const e=state.exam;if(!e||e.cards[e.index].choice===null)return;if(e.index===32)finishExam();else e.index++;save();exam();window.scrollTo(0,0)}
function pickTrivia(cat,level,excluded=[]){const pool=TRIVIA.filter(x=>x.category===cat&&x.difficulty===level&&!excluded.includes(x.id));if(!pool.length)throw Error('No unused trivia questions for this category and difficulty');const unseen=pool.filter(x=>!state.recentTrivia.includes(x.id));return shuffle(unseen.length?unseen:pool)[0]}
const TRIVIA_ICONS={'history-politics':'clock','sports':'ball','music-artists':'music','film-tv-pop':'film','art-literature-philosophy':'brush','everyday-germany':'pin'};
function startTrivia(mode){if(mode==='quick'){const cats=shuffle(Object.keys(LABELS)),weighted=()=>{const n=Math.random();return n<.45?'easy':n<.9?'medium':'hard'},levels=shuffle(['easy','medium',...Array.from({length:4},weighted)]);state.trivia={mode:'quick',cards:cats.map((cat,i)=>cardFor(pickTrivia(cat,levels[i]))),index:0,correct:0,finished:false,phase:'question'};save();trivia();return}
state.trivia={mode:'long',lives:TRIVIA_START_LIVES,streak:0,correct:0,answered:0,slices:[],phase:'roll',finished:false,card:null,levelBag:[],rollCategory:null,usedIds:[]};save();trivia()}
function triviaRoll(){const t=state.trivia;if(!t||t.mode!=='long'||t.phase!=='roll'||t.finished)return;if(!t.levelBag.length)t.levelBag=shuffle(['easy','easy','easy','easy','medium','medium','medium','medium','hard']);const cat=shuffle(Object.keys(LABELS))[0],level=t.levelBag.pop(),used=t.usedIds||[];let available=TRIVIA.filter(x=>x.category===cat&&x.difficulty===level&&!used.includes(x.id));if(!available.length)available=TRIVIA.filter(x=>x.category===cat&&!used.includes(x.id));if(!available.length){toast('You have played every question from this category. What a legend.');return}const q=pickTrivia(cat,available[0].difficulty,used);t.usedIds=[...used,q.id];t.rollCategory=cat;t.card=cardFor(q);t.phase='question';save();trivia()}
function answerTrivia(index){const t=state.trivia;if(!t||t.finished||t.phase!=='question')return;const card=t.mode==='quick'?t.cards[t.index]:t.card;if(card.choice!==null)return;const q=triviaById(card.id),right=index===q.correct_index;card.choice=index;t.lastSensitive=isSensitive(q);markSeen('trivia',q.id);t.answered=(t.answered||0)+1;if(right)t.correct++;
if(t.mode==='quick'){if(!right||t.index===5)t.finished=true;t.phase='feedback'}else{t.bonusEarned=false;t.bonusCapped=false;if(right){t.streak++;if(!t.slices.includes(q.category))t.slices.push(q.category);if(t.streak===3){t.bonusCapped=t.lives>=TRIVIA_MAX_LIVES;t.lives=Math.min(TRIVIA_MAX_LIVES,t.lives+1);t.streak=0;t.bonusEarned=true}}else{t.lives--;t.streak=0}if(t.lives===0||t.slices.length===6)t.finished=true;t.phase='feedback'}
save();trivia()}
function triviaNext(){const t=state.trivia;if(!t||t.phase!=='feedback')return;if(t.finished){const win=t.mode==='quick'?t.correct===6:t.slices.length===6&&t.lives>0;state.triviaHistory.unshift({mode:t.mode,date:localDay(),correct:t.correct,answered:t.answered,win});state.triviaHistory=state.triviaHistory.slice(0,30);if(win)state.trophies[t.mode]=(state.trophies[t.mode]||0)+1;t.phase='result';save();trivia();return}if(t.mode==='quick'){t.index++;t.phase='question'}else{t.phase='roll';t.card=null;t.bonusEarned=false;t.bonusCapped=false}save();trivia()}
function quitTrivia(){const t=state.trivia;if(!t||t.phase==='result'||t.finished)return;if(!window.confirm('Finish this round now? It will count as a loss; no trophy.'))return;t.finished=true;t.abandoned=true;t.phase='feedback';triviaNext()}
function trivia(){const t=state.trivia;const triviaOpeners=[["Capy's Trivia Night",'Six slices of Germany. Capy is watching.'],["Capy's brainy little detour",'Six categories. One capybara with opinions.'],["Tonight we quiz",'The extra game called. It wants your brain.'],["Six slices, zero chill",'History, pop culture, and Capy judging quietly.'],["The great German guessing game",'A die, a dream, and a very observant capybara.']];const [opener,openerSub]=triviaOpeners[dayIndex()%5];$('triviaHeading').textContent=t?.mode==='quick'?'Quick Round':t?.mode==='long'?'Long Run':opener;$('triviaSub').textContent=t?.mode==='quick'?'Six categories. Six questions. One mistake and the round ends.':t?.mode==='long'?'Roll for a category. Gather six slices before your lives run out.':openerSub;
if(!t){$('triviaContent').innerHTML=`<div class="cards"><button data-action="trivia-start-quick"><span>${icon('bolt')}</span><strong>Quick Round</strong><small>Six categories · 6/6 to win · no die</small></button><button data-action="trivia-start-long"><span>${icon('dice')}</span><strong>Long Run</strong><small>Roll the die · ${TRIVIA_START_LIVES} lives · collect all six slices</small></button></div>${face('neutral',line('neutral'))}${awardsHTML()}`;return}
if(t.phase==='result'){const win=t.mode==='quick'?t.correct===6:t.slices.length===6&&t.lives>0;const recap=!win&&t.mode==='quick'?`<div class="quick-recap"><span class="eyebrow">NEXT TARGET</span><strong>Get ${Math.min(6,t.correct+1)} of 6 next time.</strong><div class="mini-progress" aria-label="${t.correct} of 6 correct">${Array.from({length:6},(_,i)=>`<i class="${i<t.correct?'done':''}"></i>`).join('')}</div></div>`:'';$('triviaContent').innerHTML=`<div class="result"><span class="eyebrow">${win?'ROUND WON · TROPHY EARNED':'ROUND OVER'}</span><p class="big-score">${t.mode==='quick'?t.correct+'/6':t.slices.length+'/6 slices'}</p><p>${t.mode==='quick'?'One question from each category.':`${t.correct} correct from ${t.answered} answers · ${t.lives} lives left.`}</p>${recap}${t.lastSensitive?face('neutral','Take a breath. History deserves care.'):face(win?'win':'lose')}<div class="actions"><button class="primary" data-action="trivia-start-${t.mode}">Play again →</button><button class="ghost" data-action="trivia-menu">Other round</button></div></div>${win?awardsHTML():t.mode==='long'?awardsHTML():''}`;return}
if(t.mode==='long'&&t.phase==='roll'){$('triviaContent').innerHTML=`${statusHTML(t)}${face('neutral','Roll it. Six slices, one very observant capybara.')}<button class="die" data-action="trivia-roll" aria-label="Roll the six-sided die">🎲 Roll for a question →</button><button class="exit-round" data-action="trivia-finish">Finish game</button>`;return}
const card=t.mode==='quick'?t.cards[t.index]:t.card,q=triviaById(card.id),info=t.mode==='quick'?`QUESTION ${t.index+1}/6 · ${esc(LABELS[q.category])} · ${esc(q.difficulty)}`:`🎲 ${esc(LABELS[q.category])} · ${esc(q.difficulty)}`;
$('triviaContent').innerHTML=`${statusHTML(t)}<p class="eyebrow">${info}</p>${answerMarkup(q,card,'trivia')}${t.mode==='long'&&t.phase==='feedback'&&t.bonusEarned?`<p class="bonus-earned">Three right in a row! ${t.bonusCapped?`You reached the ${TRIVIA_MAX_LIVES}-life maximum.`:'+1 life earned.'}</p>`:''}${t.phase==='feedback'?`<div class="actions"><button class="primary" data-action="trivia-next">${t.finished?'See results →':t.mode==='long'?'Roll for the next one →':'Next question →'}</button></div>`:''}${!t.finished?`<button class="exit-round" data-action="trivia-finish">Finish game</button>`:''}`;}
function statusHTML(t){if(t.mode==='quick')return `<div class="stats"><div><b>${t.correct}/6</b><small>right so far</small></div><div><b>${Math.max(0,6-t.index)}</b><small>questions left</small></div><div><b>🏆</b><small>only at 6/6</small></div></div>`;const bonus=t.bonusEarned?3:t.streak;return `<div class="result trivia-status"><div class="trivia-status-top"><div><div class="life-hearts" aria-label="${t.lives} of ${TRIVIA_MAX_LIVES} lives">${'♥'.repeat(t.lives)}</div><div class="status-sub">${t.lives} / ${TRIVIA_MAX_LIVES} lives</div></div><div><div class="bonus-title">BONUS · +1 LIFE</div><div class="bonus-bars" aria-label="${bonus} of 3 in a row">${Array.from({length:3},(_,i)=>`<i class="${i<bonus?'done':''}"></i>`).join('')}</div><div class="status-sub">${t.bonusEarned?(t.bonusCapped?`Max ${TRIVIA_MAX_LIVES} lives`:'Life earned!'):`${bonus}/3 right in a row`}</div></div></div><div class="slices">${Object.keys(LABELS).map(c=>`<span class="slice ${t.slices.includes(c)?'earned':''}">${icon(TRIVIA_ICONS[c])}<span class="slice-label">${esc(LABELS[c])}</span></span>`).join('')}</div></div>`}
function awardsHTML(){const quick=state.trophies.quick||0,long=state.trophies.long||0;return `<details class="awards"><summary><span class="trophy-marker" aria-hidden="true">${quick+long?'🏆':'🔒'}</span><span class="award-heading"><strong>Your trophies</strong><small>${quick+long?`Quick Round ${quick} · Long Run ${long}`:'Win a round to earn one'}</small></span><span class="award-chevron" aria-hidden="true">⌄</span></summary><div class="award-rows"><div class="award-row"><span aria-hidden="true">${quick?'🏆':'🔒'}</span>${quick?`Quick Round · ${quick} ${quick===1?'win':'wins'}`:'Quick Round · 6/6 to unlock'}</div><div class="award-row"><span aria-hidden="true">${long?'🏆':'🔒'}</span>${long?`Long Run · ${long} ${long===1?'win':'wins'}`:'Long Run · six slices to unlock'}</div></div></details>`}
function render(){if(currentScreen==='home')home();if(currentScreen==='daily')daily();if(currentScreen==='study')study();if(currentScreen==='exam')exam();if(currentScreen==='trivia')trivia()}
function syncStatePickers(){for(const id of ['statePicker','settingState']){const el=$(id);if(el&&el.options.length!==STATES.length)el.innerHTML=STATES.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');if(el)el.value=state.settings.state}}
document.addEventListener('click',ev=>{const target=ev.target.closest('button');if(!target)return;if(target.dataset.go){go(target.dataset.go);return}if(target.dataset.topic){studyTopic=target.dataset.topic;studyCard=null;studyNumber=0;go('study');return}if(target.dataset.answerMode){const i=Number(target.dataset.answer);({daily:answerDaily,study:(j)=>{if(!studyCard||studyCard.choice!==null)return;studyCard.choice=j;markSeen('official',studyCard.id);masterCorrect(studyCard.id,j);save();study()},exam:examAnswer,trivia:answerTrivia})[target.dataset.answerMode]?.(i);return}const a=target.dataset.action;if(a==='daily-next')nextDaily();else if(a==='study-next')nextStudy();else if(a==='exam-new')startExam();else if(a==='exam-next')examNext();else if(a==='exam-finish')quitExam();else if(a==='trivia-start-quick')startTrivia('quick');else if(a==='trivia-start-long')startTrivia('long');else if(a==='trivia-roll')triviaRoll();else if(a==='trivia-next')triviaNext();else if(a==='trivia-finish')quitTrivia();else if(a==='trivia-menu'){state.trivia=null;save();trivia()}});
$('factReveal').onclick=()=>{const d=$('factDetail');d.classList.toggle('hidden');const open=!d.classList.contains('hidden');$('factReveal').textContent=open?'Hide story ↑':'Tell me more →';$('factReveal').setAttribute('aria-expanded',String(open));$('factSource').classList.toggle('hidden',!open||$('factSource').dataset.available!=='1')};
$('settingsButton').onclick=()=>{syncStatePickers();$('nameSetting').value=state.settings.name||'';$('humourSetting').value=state.settings.humour;$('translationSetting').checked=state.settings.translations;$('reminderSetting').checked=state.settings.reminders;$('settingsDialog').showModal()};
$('saveSettings').onclick=ev=>{const name=$('nameSetting').value.trim();if(!name){ev.preventDefault();$('nameSetting').focus();return}state.settings={name,state:$('settingState').value,humour:$('humourSetting').value,reminders:$('reminderSetting').checked,translations:$('translationSetting').checked};save();render();toast('Settings saved. Capy has taken notes.')};
$('resetMastered').onclick=()=>{if(!window.confirm('Reset question progress for all states? Your daily streak, exam results and trophies will stay.'))return;state.mastered=[];save();render();toast('Question progress reset. Your other results are safe.')};
$('welcomeForm').onsubmit=ev=>{ev.preventDefault();const name=$('welcomeName').value.trim();if(!name){$('welcomeName').focus();return}state.settings.name=name;save();$('welcomeDialog').close();home()};
$('statePicker').onchange=ev=>{state.settings.state=ev.target.value;save();syncStatePickers();render();toast('State updated. New rounds will use '+state.settings.state+'.')};
setInterval(()=>{if(currentScreen==='exam'&&state.exam&&!state.exam.finished)exam()},60000);
document.querySelectorAll('[data-nav-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.navIcon==='daily'?'flame':el.dataset.navIcon==='study'?'book':el.dataset.navIcon==='trivia'?'dice':el.dataset.navIcon)});
syncStatePickers();go('home');if(!state.settings.name)requestAnimationFrame(()=>$('welcomeDialog').showModal());
})();
