const STORAGE_KEY = 'capi-einburgerung-v2';
const today = () => new Date().toISOString().slice(0,10);
const defaultState = { answered: {}, dates: [], favorites: [], correct: 0, total: 0 };
let state = {...defaultState, ...(JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || {})};
let currentQuestion = null, studyAnswered = false, exam = {questions:[], index:0, score:0, timer:null, seconds:3600};
const $ = id => document.getElementById(id);
const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
const uniqueQuestions = () => window.QUESTIONS.filter(q => q.state === 'general' || q.state === 'berlin');
function streak() { const days = new Set(state.dates); let count=0, cursor=new Date(); while(days.has(cursor.toISOString().slice(0,10))) { count++; cursor.setDate(cursor.getDate()-1); } return count; }
function hasAnsweredToday() { return state.dates.includes(today()); }
function capi(text) { $('capiLine').textContent = text; $('studyCapiLine').textContent = text; }
function updateDashboard() { const qs=uniqueQuestions(); const answeredIds=Object.keys(state.answered).length; $('streakValue').textContent=streak(); $('correctValue').textContent=state.total ? Math.round(state.correct/state.total*100)+'%' : '0%'; $('favoriteValue').textContent=state.favorites.length; $('progressLabel').textContent=`${answeredIds} / ${qs.length}`; $('progressBar').style.width=Math.min(100,answeredIds/qs.length*100)+'%'; $('dailyReminder').classList.toggle('hidden',hasAnsweredToday()); renderCategories(); renderFavorites(); }
function renderCategories(){ const cats=[['Democracy','Voting, rights and rules','⚖'],['Politics','Institutions and government','🏛'],['History','What happened before','◷'],['Society','Life in Germany','◎'],['Berlin','Your 10 local questions','★']]; $('categoryGrid').innerHTML=cats.map(([name,desc,icon])=>`<button class="category-card" data-category="${name}"><b>${icon}</b><strong>${name}</strong><span>${desc}</span></button>`).join(''); document.querySelectorAll('.category-card').forEach(b=>b.onclick=()=>startStudy(b.dataset.category)); }
function setScreen(name){ document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active')); $(name+'Screen').classList.add('active'); document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===name)); if(name==='dashboard') updateDashboard(); if(name==='favorites') renderFavorites(); }
function getStudyQuestion(category){ let pool=uniqueQuestions().filter(q=>!category || q.category===category); if(!pool.length) pool=uniqueQuestions(); const unlearned=pool.filter(q=>!state.answered[q.id]); return [...(unlearned.length?unlearned:pool)].sort(()=>Math.random()-.5)[0]; }
function startStudy(category){ setScreen('study'); currentQuestion=getStudyQuestion(category); studyAnswered=false; renderStudy(); }
function renderStudy(){ const q=currentQuestion; $('studyCounter').textContent=`Question ${q.id}`; $('questionCategory').textContent=q.category.toUpperCase(); $('questionNumber').textContent=String(q.id).padStart(2,'0'); $('questionText').textContent=q.text; $('answerFeedback').classList.add('hidden'); $('favoriteToggle').textContent=state.favorites.includes(q.id)?'★':'☆'; $('answerList').innerHTML=q.answers.map((a,i)=>`<button class="answer-button" data-answer="${i}"><span class="letter">${String.fromCharCode(65+i)}</span>${a}</button>`).join(''); document.querySelectorAll('#answerList .answer-button').forEach(b=>b.onclick=()=>answerStudy(Number(b.dataset.answer))); }
function markActivity(correct){ const d=today(); if(!state.dates.includes(d)) state.dates.push(d); state.answered[currentQuestion.id]=correct; state.total++; if(correct) state.correct++; save(); }
function answerStudy(choice){ if(studyAnswered)return; studyAnswered=true; const correct=choice===currentQuestion.correct; markActivity(correct); document.querySelectorAll('#answerList .answer-button').forEach((b,i)=>{b.disabled=true; if(i===currentQuestion.correct)b.classList.add('correct'); if(i===choice&&!correct)b.classList.add('wrong');}); const f=$('answerFeedback'); f.classList.remove('hidden'); f.innerHTML=`<strong>${correct?'That’s it, champ!':'Nope, not that one, my friend.'}</strong><br>${currentQuestion.explanation}`; capi(correct?'Look at you — that brain finally showed up.':'Germany is not going to study itself, champ.'); updateDashboard(); }
function toggleFavorite(){ if(!currentQuestion)return; const i=state.favorites.indexOf(currentQuestion.id); if(i>=0)state.favorites.splice(i,1); else state.favorites.push(currentQuestion.id); save(); $('favoriteToggle').textContent=state.favorites.includes(currentQuestion.id)?'★':'☆'; updateDashboard(); }
function renderFavorites(){ const qs=uniqueQuestions().filter(q=>state.favorites.includes(q.id)); $('favoritesList').innerHTML=qs.length?qs.map(q=>`<button class="favorite-item" data-id="${q.id}"><b>★</b><p>${q.text}</p></button>`).join(''):'<div class="empty-state">No favourites yet.<br>Capi says one of these questions is going to make you sweat.</div>'; document.querySelectorAll('.favorite-item').forEach(b=>b.onclick=()=>{currentQuestion=uniqueQuestions().find(q=>q.id===Number(b.dataset.id)); setScreen('study'); studyAnswered=false; renderStudy();}); }
function makeExam(){ const all=uniqueQuestions().sort(()=>Math.random()-.5); exam.questions=Array.from({length:33},(_,i)=>all[i%all.length]); exam.index=0; exam.score=0; exam.seconds=3600; clearInterval(exam.timer); exam.timer=setInterval(()=>{exam.seconds--; const m=Math.floor(exam.seconds/60),s=String(exam.seconds%60).padStart(2,'0'); $('examTimer').textContent=`${m}:${s}`; if(exam.seconds<=0) finishExam();},1000); setScreen('exam'); renderExam(); }
function renderExam(){ const q=exam.questions[exam.index]; $('examCategory').textContent=q.category.toUpperCase(); $('examNumber').textContent=`${exam.index+1} / 33`; $('examQuestionText').textContent=q.text; $('examProgressBar').style.width=((exam.index+1)/33*100)+'%'; $('examFeedback').classList.add('hidden'); $('examAnswerList').innerHTML=q.answers.map((a,i)=>`<button class="answer-button" data-answer="${i}"><span class="letter">${String.fromCharCode(65+i)}</span>${a}</button>`).join(''); document.querySelectorAll('#examAnswerList .answer-button').forEach(b=>b.onclick=()=>answerExam(Number(b.dataset.answer))); }
function answerExam(choice){ const q=exam.questions[exam.index]; if(choice===q.correct) exam.score++; document.querySelectorAll('#examAnswerList .answer-button').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');if(i===choice&&choice!==q.correct)b.classList.add('wrong');}); setTimeout(()=>{exam.index++; if(exam.index>=33)finishExam(); else renderExam();},350); }
function finishExam(){ clearInterval(exam.timer); const pass=exam.score>=17; $('examQuestionText').textContent=pass?'You passed, citizen!':'Capi is sending you back to study.'; $('examAnswerList').innerHTML=`<div class="feedback">You scored <strong>${exam.score} out of 33</strong>. ${pass?'You are on the right track.':'You need 17 to pass. Don’t give up now.'}</div>`; $('finishExamButton').classList.remove('hidden'); $('finishExamButton').onclick=()=>setScreen('dashboard'); }
document.querySelectorAll('[data-action="dashboard"]').forEach(b=>b.onclick=()=>setScreen('dashboard')); document.querySelectorAll('[data-action="start-study"]').forEach(b=>b.onclick=()=>startStudy()); document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav; if(n==='study')startStudy(); else if(n==='exam')makeExam(); else setScreen(n);}); $('favoriteToggle').onclick=toggleFavorite; $('settingsButton').onclick=()=>alert('Coming soon: language, reminder time and Capi’s humour settings.'); updateDashboard();
